# frozen_string_literal: true

require "spec_helper"

RSpec.describe Mana::Compiler do
  let(:cache_dir) { Dir.mktmpdir("mana_test_cache") }

  before do
    described_class.cache_dir = cache_dir
    described_class.clear!
    Mana.config.api_key = "test-key"
  end

  after do
    FileUtils.rm_rf(cache_dir)
  end

  describe ".generate" do
    it "calls the engine and returns generated code" do
      stub_anthropic_sequence(
        [{ type: "tool_use", id: "t1", name: "write_var",
           input: { "name" => "code", "value" => "def greet(name)\n  \"Hello, \#{name}\"\nend" } }],
        [{ type: "tool_use", id: "t2", name: "done", input: {} }]
      )

      result = described_class.generate(:greet, "name", "greet the person by name")
      expect(result).to include("def greet")
      expect(result).to include("Hello")
    end

    it "unescapes literal \\n from LLM-generated code" do
      stub_anthropic_sequence(
        [{ type: "tool_use", id: "t1", name: "write_var",
           input: { "name" => "code", "value" => 'def add(a, b)\n  a + b\nend' } }],
        [{ type: "tool_use", id: "t2", name: "done", input: {} }]
      )

      result = described_class.generate(:add, "a, b", "add two numbers")
      expect(result).to include("def add(a, b)\n  a + b\nend")
      expect(result).not_to include('\\n')
    end
  end

  describe ".write_cache" do
    it "writes a .rb file to the cache directory" do
      source = "def add(a, b)\n  a + b\nend"
      path = described_class.write_cache(:add, source)

      expect(File.exist?(path)).to be true
      content = File.read(path)
      expect(content).to include("Auto-generated by ruby-mana")
      expect(content).to include("def add(a, b)")
    end

    it "includes owner prefix for class methods" do
      source = "def multiply(a, b)\n  a * b\nend"
      path = described_class.write_cache(:multiply, source, String)

      expect(File.basename(path)).to eq("string_multiply.rb")
    end
  end

  describe ".source" do
    it "returns nil for uncompiled methods" do
      expect(described_class.source(:nonexistent)).to be_nil
    end

    it "returns source after compilation" do
      code = "def test_method\n  42\nend"
      described_class.registry["test_method"] = code
      expect(described_class.source(:test_method)).to eq(code)
    end
  end

  describe ".clear!" do
    it "removes cache directory and clears registry" do
      FileUtils.mkdir_p(cache_dir)
      File.write(File.join(cache_dir, "test.rb"), "# test")
      described_class.registry["test"] = "code"

      described_class.clear!

      expect(Dir.exist?(cache_dir)).to be false
      expect(described_class.registry).to be_empty
    end
  end

  describe ".compile" do
    it "wraps a method for lazy compilation" do
      klass = Class.new do
        def square(n)
          ~"return n squared"
        end
      end

      # Mock generate to avoid full engine/HTTP stack
      generated_code = "def square(n)\n  n * n\nend"
      allow(described_class).to receive(:generate).and_return(generated_code)

      described_class.compile(klass, :square)

      obj = klass.new
      result = obj.square(5)
      expect(result).to eq(25)

      # Verify cache file was written
      cache_files = Dir.glob(File.join(cache_dir, "*.rb"))
      expect(cache_files.length).to eq(1)
      expect(File.read(cache_files.first)).to include("n * n")

      # Verify source is accessible
      key = "#{klass}#square"
      expect(described_class.registry[key]).to eq(generated_code)
    end
  end

  describe "cache hit / miss" do
    it "uses cache when prompt_hash matches (no LLM call)" do
      klass = Class.new do
        def cached_method(n)
          ~"return n doubled"
        end
      end

      original = klass.instance_method(:cached_method)
      params_desc = described_class.send(:describe_params, original)
      prompt = described_class.send(:extract_prompt, original)
      prompt_hash = Digest::SHA256.hexdigest("cached_method:#{params_desc}:#{prompt}")[0, 16]

      # Pre-populate cache with matching prompt_hash
      source_file = original.source_location&.first
      cache_path = described_class.cache_file_path(:cached_method, klass, source_file: source_file)
      FileUtils.mkdir_p(cache_dir)
      File.write(cache_path, "# Auto-generated by ruby-mana | prompt_hash: #{prompt_hash}\n# frozen_string_literal: true\n\ndef cached_method(n)\n  n * 2\nend\n")

      expect(described_class).not_to receive(:generate)
      described_class.compile(klass, :cached_method)

      obj = klass.new
      expect(obj.cached_method(5)).to eq(10)
    end

    it "regenerates when prompt_hash does not match (cache miss)" do
      klass = Class.new do
        def stale_method(n)
          ~"return n tripled"
        end
      end

      original = klass.instance_method(:stale_method)
      source_file = original.source_location&.first
      cache_path = described_class.cache_file_path(:stale_method, klass, source_file: source_file)
      FileUtils.mkdir_p(cache_dir)
      File.write(cache_path, "# Auto-generated by ruby-mana | prompt_hash: wrong_hash_here\n# frozen_string_literal: true\n\ndef stale_method(n)\n  n * 2\nend\n")

      generated_code = "def stale_method(n)\n  n * 3\nend"
      allow(described_class).to receive(:generate).and_return(generated_code)

      described_class.compile(klass, :stale_method)

      obj = klass.new
      expect(obj.stale_method(5)).to eq(15)
      expect(described_class).to have_received(:generate)
    end

    it "uses cache in IRB with weak key (method_name + params)" do
      klass = Class.new do
        def irb_method(n)
          ~"some prompt"
        end
      end

      # Simulate IRB: extract_prompt returns nil
      allow(described_class).to receive(:extract_prompt).and_return(nil)

      # Compute the weak hash (no prompt content)
      params_desc = described_class.send(:describe_params, klass.instance_method(:irb_method))
      weak_hash = Digest::SHA256.hexdigest("irb_method:#{params_desc}")[0, 16]

      # Pre-populate cache with matching weak hash
      source_file = klass.instance_method(:irb_method).source_location&.first
      cache_path = described_class.cache_file_path(:irb_method, klass, source_file: source_file)
      FileUtils.mkdir_p(cache_dir)
      File.write(cache_path, "# Auto-generated by ruby-mana | prompt_hash: #{weak_hash}\n\ndef irb_method(n)\n  n * 99\nend\n")

      # Should use cache (weak key matches), NOT call generate
      expect(described_class).not_to receive(:generate)
      described_class.compile(klass, :irb_method)

      obj = klass.new
      expect(obj.irb_method(5)).to eq(495)  # uses cached version (n*99)
    end

    it "invalidates IRB cache when method params change" do
      klass = Class.new do
        def irb_method2(a, b)
          ~"some prompt"
        end
      end

      allow(described_class).to receive(:extract_prompt).and_return(nil)

      # Cache was written with different params (just "n")
      old_hash = Digest::SHA256.hexdigest("irb_method2:n")[0, 16]
      source_file = klass.instance_method(:irb_method2).source_location&.first
      cache_path = described_class.cache_file_path(:irb_method2, klass, source_file: source_file)
      FileUtils.mkdir_p(cache_dir)
      File.write(cache_path, "# Auto-generated by ruby-mana | prompt_hash: #{old_hash}\n\ndef irb_method2(n)\n  n\nend\n")

      generated_code = "def irb_method2(a, b)\n  a + b\nend"
      allow(described_class).to receive(:generate).and_return(generated_code)

      described_class.compile(klass, :irb_method2)

      obj = klass.new
      expect(obj.irb_method2(3, 4)).to eq(7)  # regenerated, not cached
      expect(described_class).to have_received(:generate)
    end
  end

  describe ".extract_prompt" do
    it "extracts prompt from ~\"...\" expression" do
      tmpfile = Tempfile.new(["mana_test", ".rb"])
      tmpfile.write("def foo\n  ~\"my prompt\"\nend\n")
      tmpfile.rewind

      # Create a class that has a method at that source location
      klass = Class.new
      # We can test via the private method directly with a mock unbound method
      mock_method = double("unbound_method", source_location: [tmpfile.path, 1])
      result = described_class.send(:extract_prompt, mock_method)
      expect(result).to eq("my prompt")
    ensure
      tmpfile.close
      tmpfile.unlink
    end
  end

  describe ".cache_file_path" do
    it "slugifies source file path in filename" do
      path = described_class.cache_file_path(:calculate, nil, source_file: "#{Dir.pwd}/lib/foo/bar.rb")
      expect(File.basename(path)).to eq("lib_foo_bar_calculate.rb")
    end
  end

  describe ".underscore" do
    it "converts MyClass::Foo to my_class_foo" do
      expect(described_class.send(:underscore, "MyClass::Foo")).to eq("my_class_foo")
    end

    it "returns 'anonymous' for nil" do
      expect(described_class.send(:underscore, nil)).to eq("anonymous")
    end
  end

  describe "describe_params" do
    it "handles various parameter types" do
      klass = Class.new do
        def complex(a, b = 1, *rest, key:, opt: nil, **kwargs, &block); end
      end

      method = klass.instance_method(:complex)
      result = described_class.send(:describe_params, method)
      expect(result).to eq("a, b=nil, *rest, key:, opt: nil, **kwargs, &block")
    end

    it "handles no parameters" do
      klass = Class.new do
        def simple; end
      end

      method = klass.instance_method(:simple)
      result = described_class.send(:describe_params, method)
      expect(result).to eq("")
    end
  end
end
