#!/usr/bin/env bash
set -euo pipefail

ISSUE_NUMBER="${1:?Usage: ./scripts/fix-issue.sh <issue-number>}"
REPO="twokidsCarl/ruby-mana"

# 1. 读取 issue 内容
echo "📖 Reading issue #${ISSUE_NUMBER}..."
ISSUE_BODY=$(gh issue view "$ISSUE_NUMBER" --repo "$REPO" --json title,body,labels,comments --jq '
  "Title: " + .title + "\n\n" +
  "Body:\n" + .body + "\n\n" +
  "Labels: " + ([.labels[].name] | join(", ")) + "\n\n" +
  "Comments:\n" + ([.comments[].body] | join("\n---\n"))
')

# 2. 创建修复分支
BRANCH="fix/issue-${ISSUE_NUMBER}"
git checkout -b "$BRANCH" main

# 3. 用 Claude Code 无头模式分析并修复
echo "🤖 Asking Claude to fix the issue..."
claude -p "$(cat <<EOF
You are working on the ruby-mana project (a Ruby gem that embeds LLMs as native Ruby constructs).

Here is a GitHub issue that needs to be fixed:

${ISSUE_BODY}

Please:
1. Analyze the issue and understand the root cause
2. Find the relevant code files
3. Fix the code
4. Run the tests with: bundle exec rspec
5. If tests pass, commit the changes with a message referencing issue #${ISSUE_NUMBER}
6. Do NOT push or create a PR — I will handle that
EOF
)" --allowedTools 'Bash,Read,Write,Edit,Glob,Grep'

# 4. 推送并创建 PR
echo "🚀 Creating PR..."
git push -u origin "$BRANCH"
gh pr create \
  --repo "$REPO" \
  --title "Fix #${ISSUE_NUMBER}" \
  --body "$(cat <<EOF
Closes #${ISSUE_NUMBER}

## Summary
Automated fix generated by Claude Code.

## Test plan
- [ ] CI passes
- [ ] Manual verification

🤖 Generated with [Claude Code](https://claude.com/claude-code)
EOF
)" \
  --base main

echo "✅ Done! PR created for issue #${ISSUE_NUMBER}"
